"""add_document_chunk_table

Revision ID: 1e86a2a022bc
Revises: 20628f7b78f8
Create Date: 2026-06-07 19:17:28.378992

"""
from typing import Sequence, Union

from pgvector.sqlalchemy import VECTOR
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e86a2a022bc'
down_revision: Union[str, Sequence[str], None] = '20628f7b78f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.TEXT(), nullable=False),
    sa.Column('enriched_content', sa.TEXT(), nullable=False),
    sa.Column('heading_path', sa.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('embedding', VECTOR(dim=768), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['content_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunk_chunk_index'), 'document_chunk', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunk_document_id'), 'document_chunk', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunk_document_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_chunk_index'), table_name='document_chunk')
    op.drop_table('document_chunk')
    # ### end Alembic commands ###
