"""BD_v1

Revision ID: 20628f7b78f8
Revises: 
Create Date: 2026-06-02 18:13:19.896277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20628f7b78f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bloom_level',
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('level')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_user_id'), 'course', ['user_id'], unique=False)
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_course_id'), 'quiz', ['course_id'], unique=False)
    op.create_index(op.f('ix_quiz_user_id'), 'quiz', ['user_id'], unique=False)
    op.create_table('user_achievement',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_index(op.f('ix_user_achievement_achievement_id'), 'user_achievement', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievement_user_id'), 'user_achievement', ['user_id'], unique=False)
    op.create_table('content_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_document_course_id'), 'content_document', ['course_id'], unique=False)
    op.create_index(op.f('ix_content_document_user_id'), 'content_document', ['user_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bloom_level', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bloom_level'), 'question', ['bloom_level'], unique=False)
    op.create_index(op.f('ix_question_quiz_id'), 'question', ['quiz_id'], unique=False)
    op.create_table('quiz_attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempt_quiz_id'), 'quiz_attempt', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_user_id'), 'quiz_attempt', ['user_id'], unique=False)
    op.create_table('user_bloom_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('correct_questions', sa.Integer(), nullable=False),
    sa.Column('incorrect_questions', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('remember_percentage', sa.Numeric(precision=2, scale=10), nullable=True),
    sa.Column('understand_percentage', sa.Numeric(precision=2, scale=10), nullable=True),
    sa.Column('apply_percentage', sa.Numeric(precision=2, scale=10), nullable=True),
    sa.Column('analyze_percentage', sa.Numeric(precision=2, scale=10), nullable=True),
    sa.Column('evaluate_percentage', sa.Numeric(precision=2, scale=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bloom_stats_course_id'), 'user_bloom_stats', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_bloom_stats_user_id'), 'user_bloom_stats', ['user_id'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_question_id'), 'answer', ['question_id'], unique=False)
    op.create_table('quiz_source_document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['content_document.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_source_document_document_id'), 'quiz_source_document', ['document_id'], unique=False)
    op.create_index(op.f('ix_quiz_source_document_quiz_id'), 'quiz_source_document', ['quiz_id'], unique=False)
    op.create_table('question_attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score_obtained', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempt.id'], ),
    sa.ForeignKeyConstraint(['selected_answer_id'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_attempt_question_id'), 'question_attempt', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_attempt_quiz_attempt_id'), 'question_attempt', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_question_attempt_selected_answer_id'), 'question_attempt', ['selected_answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_attempt_selected_answer_id'), table_name='question_attempt')
    op.drop_index(op.f('ix_question_attempt_quiz_attempt_id'), table_name='question_attempt')
    op.drop_index(op.f('ix_question_attempt_question_id'), table_name='question_attempt')
    op.drop_table('question_attempt')
    op.drop_index(op.f('ix_quiz_source_document_quiz_id'), table_name='quiz_source_document')
    op.drop_index(op.f('ix_quiz_source_document_document_id'), table_name='quiz_source_document')
    op.drop_table('quiz_source_document')
    op.drop_index(op.f('ix_answer_question_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_user_bloom_stats_user_id'), table_name='user_bloom_stats')
    op.drop_index(op.f('ix_user_bloom_stats_course_id'), table_name='user_bloom_stats')
    op.drop_table('user_bloom_stats')
    op.drop_index(op.f('ix_quiz_attempt_user_id'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_quiz_id'), table_name='quiz_attempt')
    op.drop_table('quiz_attempt')
    op.drop_index(op.f('ix_question_quiz_id'), table_name='question')
    op.drop_index(op.f('ix_question_bloom_level'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_content_document_user_id'), table_name='content_document')
    op.drop_index(op.f('ix_content_document_course_id'), table_name='content_document')
    op.drop_table('content_document')
    op.drop_index(op.f('ix_user_achievement_user_id'), table_name='user_achievement')
    op.drop_index(op.f('ix_user_achievement_achievement_id'), table_name='user_achievement')
    op.drop_table('user_achievement')
    op.drop_index(op.f('ix_quiz_user_id'), table_name='quiz')
    op.drop_index(op.f('ix_quiz_course_id'), table_name='quiz')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_course_user_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('bloom_level')
    op.drop_table('achievement')
    # ### end Alembic commands ###
