"""add attributes to content_document table

Revision ID: 20d8ae73e434
Revises: 1e86a2a022bc
Create Date: 2026-06-17 17:45:15.952281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d8ae73e434'
down_revision: Union[str, Sequence[str], None] = '1e86a2a022bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_document', sa.Column('document_type', sa.String(length=50), nullable=False))
    op.add_column('content_document', sa.Column('processing_status', sa.String(length=50), nullable=False))
    op.add_column('content_document', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_document', 'processed_at')
    op.drop_column('content_document', 'processing_status')
    op.drop_column('content_document', 'document_type')
    # ### end Alembic commands ###
