"""Add gamification columns to user and achievements

Revision ID: 5fb52686cd0a
Revises: b1a2f4e146c6
Create Date: 2026-07-04 17:49:25.498161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb52686cd0a'
down_revision: Union[str, Sequence[str], None] = 'b1a2f4e146c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement', sa.Column('required_progress', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('streak_updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_streak_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('best_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_achievement', sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_achievement', 'progress')
    op.drop_column('user', 'best_streak')
    op.drop_column('user', 'current_streak')
    op.drop_column('user', 'last_streak_date')
    op.drop_column('user', 'streak_updated_at')
    op.drop_column('achievement', 'required_progress')
    # ### end Alembic commands ###
