"""add max_score and index submitted_at to quiz_attempt

Revision ID: b1a2f4e146c6
Revises: df2843ad4a42
Create Date: 2026-07-04 12:19:26.740973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a2f4e146c6'
down_revision: Union[str, Sequence[str], None] = 'df2843ad4a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('max_score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quiz_attempt_submitted_at'), 'quiz_attempt', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_attempt_submitted_at'), table_name='quiz_attempt')
    op.drop_column('quiz', 'max_score')
    # ### end Alembic commands ###
