"""create analytics aggregates

Revision ID: df2843ad4a42
Revises: f569c944aae0
Create Date: 2026-06-30 13:52:17.113578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df2843ad4a42'
down_revision: Union[str, Sequence[str], None] = 'f569c944aae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloom_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('bloom_level', sa.String(length=20), nullable=False),
    sa.Column('questions_attempted', sa.Integer(), nullable=False),
    sa.Column('questions_correct', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'bloom_level', name='uq_bloom_stats_course_bloom')
    )
    op.create_index(op.f('ix_bloom_stats_course_id'), 'bloom_stats', ['course_id'], unique=False)
    op.create_table('course_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('quizzes_completed', sa.Integer(), nullable=False),
    sa.Column('questions_attempted', sa.Integer(), nullable=False),
    sa.Column('questions_correct', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', name='uq_course_stats_course_id')
    )
    op.create_index(op.f('ix_course_stats_course_id'), 'course_stats', ['course_id'], unique=False)
    op.drop_index(op.f('ix_user_bloom_stats_course_id'), table_name='user_bloom_stats')
    op.drop_index(op.f('ix_user_bloom_stats_user_id'), table_name='user_bloom_stats')
    op.drop_table('user_bloom_stats')
    op.drop_constraint(op.f('content_document_course_id_fkey'), 'content_document', type_='foreignkey')
    op.create_foreign_key(None, 'content_document', 'course', ['course_id'], ['id'])
    op.alter_column('user', 'auth_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'college',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'major',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'major',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'college',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'auth_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'content_document', type_='foreignkey')
    op.create_foreign_key(op.f('content_document_course_id_fkey'), 'content_document', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_table('user_bloom_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('incorrect_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remember_percentage', sa.NUMERIC(precision=2, scale=10), autoincrement=False, nullable=True),
    sa.Column('understand_percentage', sa.NUMERIC(precision=2, scale=10), autoincrement=False, nullable=True),
    sa.Column('apply_percentage', sa.NUMERIC(precision=2, scale=10), autoincrement=False, nullable=True),
    sa.Column('analyze_percentage', sa.NUMERIC(precision=2, scale=10), autoincrement=False, nullable=True),
    sa.Column('evaluate_percentage', sa.NUMERIC(precision=2, scale=10), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('user_bloom_stats_course_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_bloom_stats_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_bloom_stats_pkey'))
    )
    op.create_index(op.f('ix_user_bloom_stats_user_id'), 'user_bloom_stats', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_bloom_stats_course_id'), 'user_bloom_stats', ['course_id'], unique=False)
    op.drop_index(op.f('ix_course_stats_course_id'), table_name='course_stats')
    op.drop_table('course_stats')
    op.drop_index(op.f('ix_bloom_stats_course_id'), table_name='bloom_stats')
    op.drop_table('bloom_stats')
    # ### end Alembic commands ###
