"""add_attributes_to_user_table

Revision ID: f89e6d492bb9
Revises: f7dda819b69e
Create Date: 2026-06-25 22:13:34.507034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89e6d492bb9'
down_revision: Union[str, Sequence[str], None] = 'f7dda819b69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_id', sa.UUID(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('college', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('major', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_user_auth_id'), 'user', ['auth_id'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_auth_id'), table_name='user')
    op.drop_column('user', 'major')
    op.drop_column('user', 'college')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'name')
    op.drop_column('user', 'auth_id')
    # ### end Alembic commands ###
